backend:
  name: github
  repo: bassio/nahdapedia

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "post"
    label: "Posts"
    label_singular: "Post"
    folder: "static/post"
    create: true
    slug: "{{slug}}"
    identifier_field: "title"
    fields:
      - {label: "id", name: "id", widget: "uuid"}
      - {label: "type", name: "type", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "date"}
      - {name: "language",
         label: "Language",
         widget: "select",
         required: true,
         options: ["en", "ar"],
         default: "en"
         }
      - {label: "Citations",
         name: "citations",
         widget: "list",
         allow_add: true,
         required: false,
         fields: [
            {name: "footnote_number",
             label: "Footnote number",
             widget: "number",
            },
            {name: "citation_comment",
             label: "Citation Comment",
             widget: "text",
            },
            {name: "citation_reference",
             label: "Citation Reference",
             widget: "relation",
             collection: "reference", 
             searchFields: ["title", "bibtex"],
             valueField: "id",
             displayFields: ["title"]
            }
             ]
         }
      - {label: "Body", name: "body", widget: "markdown"}
      
  - name: "work"
    label: "Works"
    label_singular: "Work"
    folder: "static/data/work"
    extension: "json"
    format: "json"
    create: true
    identifier_field: "title"
    slug: "{{fields.id}}"
    fields:
      - {label: "id", name: "id", widget: "uuid"}
      - {label: "type", name: "type", widget: "hidden", default: "work"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Title (Ar)", name: "title_ar", widget: "string", required: false}
      - {label: "Alternate Titles", name: "alternate_titles", widget: "list", allow_add: true, required: false,
            field: {label: "Alternate Title", name: "alt_title", widget: "string"}
         }
      - {label: "Lyrics", name: "lyrics", widget: "text", required: false}
      - {label: "Genre", name: "genre", widget: "relation",
         collection: "genre", 
         searchFields: ["name"],
         valueField: "id",
         displayFields: ["name"],
         multiple: false
         }
      - {label: "Maqam", name: "maqam", widget: "relation",
         collection: "maqam", 
         searchFields: ["name", "name_ar"],
         valueField: "id",
         displayFields: ["name", "name_ar"],
         multiple: false
         }
      - {label: "Contributors",
         name: "contributors",
         widget: "list",
         allow_add: true,
         required: false,
         fields: [
            {name: "contributor",
             label: "Contributor",
             widget: "relation",
             collection: "agent", 
             searchFields: ["name"],
             valueField: "id",
             displayFields: ["name"]},
             {name: "contributor_role",
             label: "Role",
             widget: "select",
             options: ["Composer", "Writer"]
            }
            ]
         }
      - {label: "Citations",
         name: "citations",
         widget: "list",
         allow_add: true,
         required: false,
         fields: [
            {name: "footnote_number",
             label: "Footnote number",
             widget: "number",
            },
            {name: "citation_comment",
             label: "Citation Comment",
             widget: "text",
            },
            {name: "citation_reference",
             label: "Citation Reference",
             widget: "relation",
             collection: "reference", 
             searchFields: ["title", "bibtex"],
             valueField: "id",
             displayFields: ["title"]
            }
             ]
         }

  - name: "genre"
    label: "Genres"
    label_singular: "Genre"
    folder: "static/data/genre"
    extension: "json"
    format: "json"
    create: true
    identifier_field: "name"
    slug: "{{fields.id}}"
    fields:
      - {label: "id", name: "id", widget: "uuid"}
      - {label: "type", name: "type", widget: "hidden", default: "genre"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Name (Ar)", name: "name_ar", widget: "string", required: false}

  - name: "maqam"
    label: "Maqams"
    label_singular: "Maqam"
    folder: "static/data/maqam"
    extension: "json"
    format: "json"
    create: true
    identifier_field: "name"
    slug: "{{fields.id}}"
    fields:
      - {label: "id", name: "id", widget: "uuid"}
      - {label: "type", name: "type", widget: "hidden", default: "maqam"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Name (Ar)", name: "name_ar", widget: "string", required: false}

  - name: "agent"
    label: "Agents"
    label_singular: "Agent"
    folder: "static/data/agent"
    extension: "json"
    format: "json"
    create: true
    identifier_field: "name"
    slug: "{{fields.id}}"
    fields:
      - {label: "id", name: "id", widget: "uuid"}
      - {label: "type", name: "type", widget: "hidden", default: "agent"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Name (Ar)", name: "name_ar", widget: "string", required: false}
      - {label: "Alternate Names", name: "alternate_names", widget: "list", allow_add: true, required: false,
            field: {label: "Alternate Name", name: "alt_name", widget: "string"}
         }
      - {name: "usual_role",
         label: "Usual Role",
         widget: "select",
         required: false,
         options: ["Artist", "Composer", "Conductor", "Musician", "Performer", "Performing Group", "Recording Engineer", "Vocalist", "Writer"]
         }

  - name: "label"
    label: "Labels"
    label_singular: "Label"
    folder: "static/data/label"
    extension: "json"
    format: "json"
    create: true
    identifier_field: "name"
    slug: "{{fields.id}}"
    fields:
      - {label: "id", name: "id", widget: "uuid"}
      - {label: "type", name: "type", widget: "hidden", default: "label"}
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Name (Ar)", name: "name_ar", widget: "string", required: false}
      - {label: "Alternate Names", name: "alternate_names", widget: "list", allow_add: true, required: false,
            field: {label: "Alternate Name", name: "alt_name", widget: "string"}
         }
      - {label: "Label Code (LC)", name: "lc", widget: "string", required: false}

  - name: "release"
    label: "Releases"
    label_singular: "Release"
    folder: "static/data/release"
    extension: "json"
    format: "json"
    create: true
    identifier_field: "title"
    slug: "{{fields.id}}"
    fields:
      - {label: "id", name: "id", widget: "uuid"}
      - {label: "type", name: "type", widget: "hidden", default: "release"}
      - {label: "Title of Release", name: "title", widget: "string"}
      - {label: "Title of Release (Ar)", name: "title_ar", widget: "string"}
      - {label: "Date of Release", name: "date", widget: "string", required: false}
      - {label: "Label", name: "label",  widget: "relation",
         collection: "label", 
         searchFields: ["name"],
         valueField: "id",
         displayFields: ["name", "name_ar"],
         multiple: false
         }
      - {label: "Catalogue Numbers", label_singular: "Catalogue Number", name: "catalogue_numbers", widget: "list", allow_add: true,
            field: {label: "Catalogue Number", name: "catalogue_number", widget: "string"}
         }
      - {label: "Release Type", name: "release_type", widget: "select", default: "Commercial", options: ["Commercial", "Prova"]}
      - {label: "Record Count", name: "record_count", widget: "number", default: 1, valueType: "int"}
      - {label: "Media Type",
         name: "media_type",
         widget: "select",
         options: ["Shellac disc [10 inch]",
                   "Shellac disc [12 inch]",
                   "Vinyl recording",
                   "Wax Cylinder"]
                   }
      - {label: "Artist", name: "artist", widget: "relation",
         collection: "agent", 
         searchFields: ["name"],
         valueField: "id",
         displayFields: ["name"],
         multiple: true
         }
      - {label: "Tracks",
         name: "tracks",
         widget: "list",
         allow_add: true,
         fields: [
           {label: "track_id", name: "id", widget: "uuid"},
           {label: "Record Number", name: "record_number", widget: "number", min: 1, default: 1, required: false},
           {label: "Side Number", name: "side_number", widget: "number", min: 1, max: 2, required: false},
           {label: "Track Number", name: "track_number", widget: "number", required: false},
           {label: "Catalogue Number", name: "catalogue_number", widget: "string", required: false},
           {label: "Matrix Number", name: "matrix_number", widget: "string", required: false},
           {label: "Work",
            name: "work",
            widget: "relation",
            collection: "work", 
            searchFields: ["title"],
            valueField: "id",
            displayFields: ["title"],
            multiple: false
            },
           {label: "Artists/Contributors",
            name: "contributors",
            widget: "list",
            allow_add: true,
            fields: [{name: "contributor",
               label: "Contributor",
               widget: "relation",
               collection: "agent", 
               searchFields: ["name"],
               valueField: "id",
               displayFields: ["name"],
               required: true},
               {name: "contributor_role",
               label: "Role",
               widget: "select",
               options: ["Artist", "Composer", "Conductor", "Musician", "Performer", "Performing Group", "Recording Engineer", "Vocalist", "Writer"]
               }
               ]
            }
         ]
      }

  - name: "reference"
    label: "References"
    label_singular: "Reference"
    folder: "static/data/reference"
    extension: "json"
    format: "json"
    create: true
    identifier_field: "title"
    slug: "{{fields.id}}"
    fields:
      - {label: "id", name: "id", widget: "uuid"}
      - {label: "type", name: "type", widget: "hidden", default: "reference"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "BibTeX entry", name: "bibtex", widget: "text", required: false}


